key_market/apps/games/urls.py
from django.conf.urls import url

from games import views as views_games
from games.models import StoreActivation


stories = [store for index, store in StoreActivation.CHOICES]

urlpatterns = [
    url(r'^games/$',
        views_games.GamesList.as_view(), name='list'),
    url(r'^games/(?P<slug>[-\w]+)/$',
        views_games.GamesDetail.as_view(), name='detail'),
    url(r'^games/(?P<slug>[-\w]+)/order/$',
        views_games.GamesOrder.as_view(), name='order'),
    url(r'^genre/(?P<slug>[-\w]+)/$',
        views_games.GamesList.as_view(), name='genre_list'),
    url(r'^mode/(?P<slug>[-\w]+)/$',
        views_games.GamesList.as_view(), name='mode_list'),
    url(r'^store/(?P<store>%s)/$' % '|'.join(stories),
        views_games.GamesStoreList.as_view(), name='store_list'),
    url(r'^lucky/$',
        views_games.GamesLucky.as_view(), name='lucky'),
]

key_market/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView, TemplateView

from rest_framework import routers

from games.views import IndexPage, SearchGameViewSet


router = routers.DefaultRouter()
router.register(r'search_game', SearchGameViewSet)

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='index'),
    url(r'^', include('games.urls', namespace='games')),
    url(r'^a441a4cc8871.html$',
        TemplateView.as_view(template_name='yandex.html')),
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^about/', include('pages.urls', namespace='pages')),
    url(r'^robots.txt$',
        TemplateView.as_view(template_name='robots.txt',
                             content_type='text/plain')),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'),
                             permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

key_market/apps/games/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

from pytils.translit import slugify


class GameLanguage(object):
        RU = 1
        ENG = 2
        CHOICES = (
            (RU, 'русский'),
            (ENG, 'английский'),
        )


class StoreActivation(object):
        STEAM = 1
        ORIGIN = 2
        UPLAY = 3
        ROCKSTAR = 4
        CHOICES = (
            (STEAM, 'steam'),
            (ORIGIN, 'origin'),
            (UPLAY, 'uplay'),
            (ROCKSTAR, 'rockstar'),
        )


class MethodActivation(object):
        STEAM_GIFT = 1
        STEAM_KEY = 2
        ORIGIN_KEY = 3
        UPLAY_KEY = 4
        ROCKSTAR_KEY = 5
        CHOICES = (
            (STEAM_GIFT, 'steam gift'),
            (STEAM_KEY, 'steam ключ'),
            (ORIGIN_KEY, 'origin ключ'),
            (UPLAY_KEY, 'uplay ключ'),
            (ROCKSTAR_KEY, 'rockstar ключ'),
        )


class RegionActivation(object):
        SNG_REGION = 1
        RU_REGION = 2
        RU_POL_REGION = 3
        CHOICES = (
            (SNG_REGION, 'Страны СНГ'),
            (RU_REGION, 'Россия'),
            (RU_POL_REGION, 'Россия/Польша'),
        )


class PartnerName(object):
        STEAMBUY = 1
        SFERA2002 = 2
        CHOICES = (
            (STEAMBUY, 'steambuy.com'),
            (SFERA2002, 'sfera2002 на plati.ru'),
        )


class Game(models.Model):
    title = models.CharField(
        'Название игры',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    description = models.TextField(
        'Описание игры',
        blank=True)

    date_created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True)

    date_release = models.DateField(
        'Дата выхода',
        blank=True, null=True)

    genre = models.ManyToManyField(
        'Genre',
        verbose_name='Жанр',
        related_name='genres',
        blank=True)

    mode = models.ManyToManyField(
        'Mode',
        verbose_name='Режим',
        related_name='modes',
        blank=True)

    publisher = models.ForeignKey(
        'Publisher',
        verbose_name='Издатель',
        related_name='publishers',
        blank=True, null=True, on_delete=models.SET_NULL)

    language = models.IntegerField(
        'Язык',
        choices=GameLanguage.CHOICES,
        db_index=True, blank=True, null=True)

    store_activation = models.IntegerField(
        'активация',
        choices=StoreActivation.CHOICES,
        db_index=True, blank=True, null=True)

    method_activation = models.IntegerField(
        'способ активации',
        choices=MethodActivation.CHOICES,
        db_index=True, blank=True, null=True)

    region = models.IntegerField(
        'Региональные ограничения',
        choices=RegionActivation.CHOICES,
        db_index=True, blank=True, null=True)

    image = models.ImageField(
        'Обложка',
        blank=True, null=True,
        upload_to='gamescover/')

    image_slide = models.ImageField(
        'Изображение для слайда',
        blank=True, null=True,
        upload_to='gamescover/')

    my_coast = models.IntegerField(
        'Стоимость в рублях',
        blank=True, null=True)

    id_video = models.CharField(
        'ID youtube ролика',
        max_length=254,
        blank=True, null=True)

    in_stock = models.BooleanField(
        'Товар в наличии',
        default=False)

    store_coast = models.IntegerField(
        'Официальная стоимость',
        blank=True, null=True)

    digiseller_id = models.IntegerField(
        'Digiseller ID',
        blank=True, null=True)

    os = models.CharField(
        'ОС',
        max_length=254,
        blank=True, null=True)

    processor = models.CharField(
        'Процессор',
        max_length=1000,
        blank=True, null=True)

    ozu = models.CharField(
        'Оперативная память',
        max_length=254,
        blank=True, null=True)

    video_card = models.CharField(
        'Видеокарта',
        max_length=1000,
        blank=True, null=True)

    hdd = models.CharField(
        'Жесткий диск',
        max_length=254,
        blank=True, null=True)

    is_slide = models.BooleanField(
        'Показать в слайде',
        default=False)

    is_soon = models.BooleanField(
        'Скоро в продаже',
        default=False)

    on_main_page = models.BooleanField(
        'Показать на главной',
        default=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        if not self.slug:
            self.slug = slugify(self.title)

    @property
    def percent(self):
        return 100 - int(self.my_coast / self.store_coast * 100)

    @property
    def gamevideo(self):
        if self.id_video:
            return mark_safe(
                '<div class="description"><h2>Трейлер игры</h2><div class="video-content"><div class="video-container"><iframe width="560" height="315" src="https://www.youtube.com/embed/{video}?rel=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div></div></div>'.format(video=self.id_video))
        return ''

    def get_absolute_url(self):
        return reverse('games:detail', args=[self.slug])


class Screenshot(models.Model):
    title = models.CharField(
        'Название игры',
        max_length=254)

    image = models.ImageField(
        'Скриншот',
        blank=True, null=True,
        upload_to='gallery/')

    game = models.ForeignKey(
        'Game',
        verbose_name='Скриншоты',
        related_name='screenshots',
        blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Скриншот'
        verbose_name_plural = 'Скриншоты'

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(
        'Название жанра',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    order = models.PositiveSmallIntegerField(
        'Порядок',
        default=0, blank=False, null=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['order']
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        self.slug = slugify(self.title)


class Mode(models.Model):
    title = models.CharField(
        'Название режима',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    order = models.PositiveSmallIntegerField(
        'Порядок',
        default=0, blank=False, null=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['order']
        verbose_name = 'Режим'
        verbose_name_plural = 'Режимы'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        self.slug = slugify(self.title)


class Publisher(models.Model):
    title = models.CharField(
        'Название издателя',
        max_length=254)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'

    def __str__(self):
        return self.title


class Partner(models.Model):
    partner_title = models.IntegerField(
        'Название партнера',
        choices=PartnerName.CHOICES,
        db_index=True, blank=True, null=True)

    partner_digi_id = models.CharField(
        'ID товара',
        max_length=254)

    game = models.ForeignKey(
        'Game',
        verbose_name='Партнеры',
        related_name='partners',
        blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['partner_title']
        verbose_name = 'Партнер'
        verbose_name_plural = 'Партнеры'

    def __str__(self):
        return self.get_partner_title_display()

key_market/apps/games/forms.py
from django import forms

from games.models import Game


class CheckboxWidget(forms.CheckboxSelectMultiple):
    template_name = 'form/checkbox.html'


class FilterForm(forms.ModelForm):
    """
    Форма для фильтрации игр по параметрам.
    """
    price_min = forms.IntegerField(
        label='Цена от',
        required=False)
    price_max = forms.IntegerField(
        label='Цена до',
        required=False)

    class Meta:
        fields = ['price_min', 'price_max', 'genre', 'store_activation',
                  'mode']
        model = Game
        widgets = {
            'genre': CheckboxWidget,
            'store_activation': CheckboxWidget,
            'mode': CheckboxWidget,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        store_field = self.fields['store_activation']
        store_field.choices = store_field.choices[1:]

key_market/apps/news/views.py
from django.views.generic import ListView, DetailView
from news.models import Item


class NewsList(ListView):
    model = Item
    template_name = "news_list.html"


class NewsDetail(DetailView):
    model = Item
    template_name = "news_detail.html"

key_market/apps/games/templates/games_detail.html
{% extends "columns_2.html" %}

{% load static pipeline %}
{% load thumbnail %}

{% block title %}Купить {{ game.title }} на PC для {{ game.get_store_activation_display }}{% endblock title %}

{% block keywords %}Купить {{ game.title }}, ключ {{ game.title }}, на pc, купить со скидкой{% endblock keywords %}

{% block description %}Купить лицензионный ключ {{ game.title }} на PC. Активация в {{ game.get_store_activation_display }}. Моментальная доставка. Игра продается со скидкой по самой низкой цене в интернете.{% endblock description %}

{% block ogtitle %}Купить {{ game.title }} на PC для {{ game.get_store_activation_display }}{% endblock ogtitle %}

{% block ogdescription %}Купить лицензионный ключ {{ game.title }} на PC. Активация в {{ game.get_store_activation_display }}. Моментальная доставка. Игра продается со скидкой по самой низкой цене в интернете.{% endblock ogdescription %}

{% block ogimg %}{{ game.image.url }}{% endblock ogimg %}


{% block extra-scripts %}
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?151"></script>
    <script type="text/javascript">
        VK.init({apiId: 6330274, onlyWidgets: true});
    </script>
{% endblock extra-scripts %}

{% block view_element %}
    <div class="game_page">
        <h1>Купить {{ game.title }} на PC</h1>
        <div class="game_head">
            <div class="game_img">
                {% thumbnail game.image "460x215" quality=100 as main_image %}
                <img src="{{ main_image.url }}">
            </div>
            <div class="game_info">
                <div class="game_detail_info">
                    <div>
                        <span>Жанр:</span>
                        <span>
                            {% for genre in game.genre.all%}
                                <a href="{% url 'games:list' %}?genre={{ genre.id }}">{{ genre.title }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </span>
                    </div>
                    <div>
                        <span>Язык:</span>
                        <span>{{ game.get_language_display }}</span>
                    </div>
                    <div>
                        <span>Активация:</span>
                        <span>
                            <a class="method-activation" href="{% url 'games:store_list' game.get_store_activation_display %}">{{ game.get_method_activation_display }}</a>
                        </span>
                    </div>
                    <div>
                        <span>Дата выхода:</span>
                        <span>{{ game.date_release|date:"SHORT_DATE_FORMAT" }}</span>
                    </div>
                    <div>
                        <span>Издатель:</span>
                        <span>{{ game.publisher }}</span>
                    </div>
                </div>
                <div class="status">
                    <div class="percent">
                        <percent>Скидка <span>-{{ game.percent }}%</span></percent>
                    </div>
                    <div class="buy">
                        <div class="coast">
                            <price>{{ game.my_coast }}<span> руб.</span></price>
                        </div>
                        {% if game.in_stock %}
                            <a class="buy_button" href="{% url 'games:order' game.slug %}">
                                <span>Купить игру</span>
                            </a>
                        {% elif game.is_soon %}
                            <div class="soon">
                                <span>Скоро!</span>
                            </div>
                        {% else %}
                            <div class="nonal">
                                <span>Закончился!</span>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="game_description">
            <div class="game_description_tabs">
                <ul class="tab_menu">
                    <li class="active">Описание</li>
                    <li>Системные требования</li>
                    <li>Активация</li>
                </ul>
            </div>
            <div class="game_description_columns">
                <div class="game_description_left">
                    <div class="tabs">
                        <div class="tab_content active">
                            <div class="description_block">
                                <h2>Описание игры</h2>
                                <div class="description_content">
                                    {{ game.description|safe }}
                                </div>
                            </div>
                        </div>
                        <div class="tab_content">
                            <div class="description_block">
                                <h2>Системные требования</h2>
                                <div class="description_content">
                                    <p>
                                    <strong>ОС:</strong> {{ game.os }}<br />
                                    <strong>Видео карта:</strong> {{ game.video_card }}<br />
                                    <strong>Процессор:</strong> {{ game.processor }}<br />
                                    <strong>ОЗУ:</strong> {{ game.ozu }}<br />
                                    <strong>HDD:</strong> {{ game.hdd }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="tab_content">
                            
                            <div class="description_block">
                                <h2>Инструкция активации</h2>
                                <div class="description_content">
                                    Находится в разработке.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="game_description_right">
                    <div class="media_block">

                        {% for screenshot in game.screenshots.all %}
                            {% if forloop.first and game.id_video %}
                                <div class="media_element">
                                    {% thumbnail screenshot.image "297x167" as im %}
                                    <img src="{{ im.url }}">
                                    <div class="video_sticker">трейлер</div>
                                    <a data-fancybox="video" class="play" data-width="830" data-height="470" href="https://www.youtube.com/watch?v={{ game.id_video }};autoplay=1&amp;rel=0&amp;controls=1&amp;showinfo=0"></a>
                                </div>
                            {% else %}
                                <div class="media_element">
                                    {% thumbnail screenshot.image "297x167" as im %}
                                    <img src="{{ im.url }}">
                                    <a data-fancybox="gallery" data-width="830" href="{{ screenshot.image.url }}"></a>
                                </div>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
            <div class="comments">
                <div id="vk_comments"></div>
                <script type="text/javascript">
                    VK.Widgets.Comments("vk_comments", {limit: 20, attach: "photo"});
                </script>
            </div>
        </div>
    </div>
{% endblock %}

key_market/apps/games/templates/games_genre_list.html
<div class="block">
    <h3>Жанр игры</h3>
    <div class="block_content">
        <ul class="menu">
            {% for genre in genre_list %}
            <li>
                <a href="{% url 'games:list' %}?genre={{ genre.id }}">{{ genre.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

key_market/apps/games/templates/games_last_pay.html
{% if last_pay %}
<div class="block">
    <h3>Недавно купили</h3>
    <div class="block_content">
        <ul class="menu">
            {% for game in last_pay %}
                <li><a href="{{ game.get_absolute_url }}">{{ game.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endif %}

key_market/apps/games/templates/games_list.html
{% extends "columns_3.html" %}
{% load thumbnail common_tags %}

{% block title %}{{ page_title }}{% endblock title %}

{% block keywords %}Ключи, {{ section }}{% endblock keywords %}

{% block description %}Описание {{ section }}{% endblock description %}


{% block left_column %}
    <div data-popup="filter" class="block filter_block">
        <div class="head_popup">
            <span class="close_popup_button">
                <i class="fa fa-times" aria-hidden="true"></i>
            </span>
        </div>
        <div class="filter">
            <form action="" method="GET">
                <div class="block_content">


                    <div class="property">
                        <div class="property_head">Цена</div>
                        <div class="property_content">
                            <div id="price"></div>
                            <div class="price_detail">
                                <span>от</span>
                                <div><input data-price-min="{{ prices.price_min }}" name="price_min" id="min-price" value="{{ filter_form.price_min.value }}"></div>
                                <span>до</span>
                                <div><input data-price-max="{{ prices.price_max }}" name="price_max" id="max-price" value="{{ filter_form.price_max.value }}"></div>
                                <span>руб.</span>
                            </div>
                        </div>
                        
                    </div>

                    <div class="property">
                        <div class="property_head">{{ filter_form.genre.label }}</div>
                        {{ filter_form.genre }}
                    </div>

                    <div class="property">
                        <div class="property_head">{{ filter_form.store_activation.label }}</div>
                        {{ filter_form.store_activation }}
                    </div>

                    <div class="property">
                        <div class="property_head">{{ filter_form.mode.label }}</div>
                        {{ filter_form.mode }}
                    </div>
                </div>
                <div class="block_button">
                    <input type="submit" value="Подобрать">
                </div>
            </form>
        </div>
    </div>
{% endblock left_column %}


{% block center_column %}
    {% if game_list %}
        <div class="wrapper_game_list">
            <div class="head_game_list">
                <h1>{{ page_title }}</h1>
                <div data-popup-button="filter" class="filter_button">
                    <i class="fa fa-sliders" aria-hidden="true"></i>
                </div>
            </div>
            <div class="game_list">
                {% for games in object_list %}
                    <div class="game">
                        <a class="link" href="{% url 'games:detail' games.slug %}"></a>
                        <div class="game_img">
                            {% thumbnail games.image "250x117" quality=100 as im %}
                            <img src="{{ im.url }}">
                        </div>
                        <div class="game_info">
                            <div class="product">
                                <div class="name">{{ games.title }}</div>
                                <div class="store_info">
                                    <div class="mini_icon mini_icon_{{ games.get_store_activation_display }}"></div>
                                </div>
                            </div>
                            <div class="status">
                                {% if games.in_stock %}
                                    <div class="coast">
                                        <div class="percent">-{{ games.percent }}%</div>
                                        <div class="price">
                                            {{ games.my_coast }} <span>руб.</span>
                                        </div>
                                    </div>
                                {% elif game.is_soon %}
                                    <div class="soon">Скоро!</div>
                                {% else %}
                                    <div class="nonal">Закончился!</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        {% if is_alphabet %}
            На такую букву игр не нашлось
        {% else %}
            В разделе {{ section }} нет ни одной игры. Приходите позже, они обязательно появятся
        {% endif %}
    {% endif %}
    {% if is_paginated %}
        {% paginator 2 %}
    {% endif %}
{% endblock %}

key_market/apps/games/templates/games_lucky.html
{% extends "columns_1.html" %}

{% load static pipeline %}

{% block title %}Купить испытай удачу, купить кейсы с ключами{% endblock title %}

{% block keywords %}купить испытай удачу, случайный ключ, купить кейс с ключами{% endblock keywords %}

{% block description %}Отличный шанс купить крутую игру, потратив минимальное количество денежных средств.{% endblock description %}

{% block extra-scripts %}
    <script type="text/javascript" src="{% static 'frontend/js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?151"></script>
    <script type="text/javascript">
        VK.init({apiId: 6330274, onlyWidgets: true});
    </script>
{% endblock extra-scripts %}

{% block view_element %}
    <div class="luckypage">
        <h1>Купить комплект с ключами</h1>
        <div class="luckyinfo">
            В данном разделе вы можете купить один из комплектов ключей, среди которых может находится очень дорогая игра. Данный раздел не является сервисом который можно приравнять к азартному. Комплекты постоянно пополняются. Каждый комплект может содержать игры новинки. В комплектах отсутствуют ключи на DLC или демо версии.
        </div>
        <div class="lucky-boxs clear-block">
            <div class="lucky-box silver">
                <h2>Silver box</h2>
                <div class="cristal"></div>
                <div class="lucky-box-price">
                    39 <span>руб.</span>
                </div>
                <div class="lucky-box-info">
                    <div>кол-во ключей: 1-2</div>
                    <div>игры до 599 руб.</div>
                </div>
                <div class="lucky-box-buy">
                    <a href="{% url 'games:order' 'silver-box' %}">Купить бокс</a>
                </div>
            </div>
            <div class="lucky-box gold">
                <h2>Gold box</h2>
                <div class="cristal"></div>
                <div class="lucky-box-price">
                    99 <span>руб.</span>
                </div>
                <div class="lucky-box-info">
                    <div>кол-во ключей: 1-5</div>
                    <div>игры до 999 руб.</div>
                </div>
                <div class="lucky-box-buy">
                    <a href="{% url 'games:order' 'gold-box' %}">Купить бокс</a>
                </div>
            </div>
            <div class="lucky-box vip">
                <h2>Vip box</h2>
                <div class="cristal"></div>
                <div class="lucky-box-price">
                    249 <span>руб.</span>
                </div>
                <div class="lucky-box-info">
                    <div>кол-во ключей: 1-2</div>
                    <div>игры до 1999 руб.</div>
                </div>
                <div class="lucky-box-buy">
                    <a href="{% url 'games:order' 'vip-box' %}">Купить бокс</a>
                </div>
            </div>
        </div>
        <div class="games-in-boxs">
            <p><strong>В любом кейсе может попасться:</strong></p>
            <p>Grand Theft Auto 5, Watch Dogs 2, Battlefield 4, Battlefield 3, Battlefield 1, Far Cry 4, Far Cry Primal, Far Cry 3, Mortal Kombat XL, Mortal Kombat X, Mortal Kombat Komplete Edition, The Evil Within 2, Warhammer 40,000: Dawn of War III, Quantum Break, Alien: Isolation, TEKKEN 7, Elex, Middle-earth: Shadow of War, Middle-earth: Shadow of Mordor, Injustice 2, Injustice: Gods Among Us Ultimate Edition, Mafia III, Fallout 4, Batman Arkham Knight, Assassin's Creed Origins, Assassin's Creed Unity, Assassin's Creed Black Flag, Assassin's Creed Syndicate, DOOM, Tom Clancy's The Division, Tom Clancy's Rainbow Six Siege, Dying Light, Prey, Dead Rising 3, Dead Rising 4, The Witcher 3: Wild Hunt, Call of Duty WWII, Call of Duty: Advanced Warfare, Call of Duty: Infinite Warfare, Call of Duty: Black Ops 3, Call of Duty: Black Ops 2, Call of Duty: Black Ops, Call of Duty: Ghosts, Call of Duty: Modern Warfare 2, Rise of the Tomb Raider, BioShock Infinite, RUST, The Forest, Ghost Recon Wildlands, Wolfenstein II: The New Colossus и др.</p>
        </div>
        <div class="lucky-comments">
            <div id="vk_comments"></div>
            <script type="text/javascript">
                VK.Widgets.Comments("vk_comments", {limit: 40, attach: "photo"});
            </script>
        </div>
    </div>
{% endblock view_element %}

key_market/apps/games/templates/games_lucky_button.html
<div class="block">
    <div class="lucky-button">
        <a href="{% url 'games:lucky' %}">Испытай удачу</a>
    </div>
</div>

key_market/apps/games/templates/games_prices.html
{% extends "base.html" %}


{% block content %}
<div class="content">
    <table cellpadding="4" width="100%">
        <tr>
            <td><strong>Название игры</strong></td>
            <td><strong>steambuy.com</strong></td>
            <td><strong>steampay.com</strong></td>
            <td><strong>steam-account.ru</strong></td>
            <td><strong>zaka-zaka.com</strong></td>
            <td><strong>steamcool.ru</strong></td>
        </tr>
        {% for games in object_list %}
            <tr>
                <td>{{ games.title }}</td>
                <td>{{ games.sb_id }}</td>
                <td>{{ games.sp_id }}</td>
                <td>{{ games.sa_id }}</td>
                <td>{{ games.zz_id }}</td>
                <td>{{ games.my_coast }} р.</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

key_market/apps/games/templates/games_soon_block.html
{% load thumbnail %}

<div class="block best-price-block">
    <h3>Скоро в продаже</h3>
    {% for special_game in soon_block %}
        <div class="special-box">

            <div class="sale-per-foto">
                {% thumbnail special_game.image "250x116" crop="center" as im %}
                <a class="sale-foto" href="{% url 'games:detail' special_game.slug %}">
                    <img src="{{ im.url }}" width="100%" alt="">
                </a>
            </div>
            <div class="clear-block">
                <div class="sale-per">Скоро</div>
                <div class="sale-coast">
                    {{ special_game.my_coast }} руб.
                </div>
            </div>
            

        </div>
    {% endfor %}
</div>