key_market/apps/games/urls.py
from django.conf.urls import url

from games import views as views_games
from games.models import StoreActivation


stories = [store for index, store in StoreActivation.CHOICES]

urlpatterns = [
    url(r'^games/$',
        views_games.GamesList.as_view(), name='list'),
    url(r'^games/(?P<slug>[-\w]+)/$',
        views_games.GamesDetail.as_view(), name='detail'),
    url(r'^games/(?P<slug>[-\w]+)/order/$',
        views_games.GamesOrder.as_view(), name='order'),
    url(r'^genre/(?P<slug>[-\w]+)/$',
        views_games.GamesList.as_view(), name='genre_list'),
    url(r'^mode/(?P<slug>[-\w]+)/$',
        views_games.GamesList.as_view(), name='mode_list'),
    url(r'^store/(?P<store>%s)/$' % '|'.join(stories),
        views_games.GamesStoreList.as_view(), name='store_list'),
    url(r'^lucky/$',
        views_games.GamesLucky.as_view(), name='lucky'),
]

key_market/apps/news/urls.py
from django.conf.urls import url
from news.views import NewsList, NewsDetail


urlpatterns = [
    url(r'^$', NewsList.as_view(), name='news'),
    url(r'^(?P<slug>[-\w]+)/$', NewsDetail.as_view(), name='readevent'),
]

key_market/apps/pages/urls.py
from django.conf.urls import url
from pages.views import ActivationPage, AgreementDoc, ReviewsPage, GuaranteePage, PaymentPage, InstructionPage, SupportPage


urlpatterns = [
    url(r'^activation/$', ActivationPage.as_view(), name='activation'),
    url(r'^agreement/$', AgreementDoc.as_view(), name='agreement'),
    url(r'^reviews/$', ReviewsPage.as_view(), name='reviews'),
    url(r'^guarantee/$', GuaranteePage.as_view(), name='guarantees'),
    url(r'^payment/$', PaymentPage.as_view(), name='payment'),
    url(r'^instruction/$', InstructionPage.as_view(), name='instruction'),
    url(r'^support/$', SupportPage.as_view(), name='support'),
]

key_market/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView, TemplateView

from rest_framework import routers

from games.views import IndexPage, SearchGameViewSet


router = routers.DefaultRouter()
router.register(r'search_game', SearchGameViewSet)

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='index'),
    url(r'^', include('games.urls', namespace='games')),
    url(r'^a441a4cc8871.html$',
        TemplateView.as_view(template_name='yandex.html')),
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^about/', include('pages.urls', namespace='pages')),
    url(r'^robots.txt$',
        TemplateView.as_view(template_name='robots.txt',
                             content_type='text/plain')),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'),
                             permanent=True)),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

key_market/apps/games/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe

from pytils.translit import slugify


class GameLanguage(object):
        RU = 1
        ENG = 2
        CHOICES = (
            (RU, 'русский'),
            (ENG, 'английский'),
        )


class StoreActivation(object):
        STEAM = 1
        ORIGIN = 2
        UPLAY = 3
        ROCKSTAR = 4
        CHOICES = (
            (STEAM, 'steam'),
            (ORIGIN, 'origin'),
            (UPLAY, 'uplay'),
            (ROCKSTAR, 'rockstar'),
        )


class MethodActivation(object):
        STEAM_GIFT = 1
        STEAM_KEY = 2
        ORIGIN_KEY = 3
        UPLAY_KEY = 4
        ROCKSTAR_KEY = 5
        CHOICES = (
            (STEAM_GIFT, 'steam gift'),
            (STEAM_KEY, 'steam ключ'),
            (ORIGIN_KEY, 'origin ключ'),
            (UPLAY_KEY, 'uplay ключ'),
            (ROCKSTAR_KEY, 'rockstar ключ'),
        )


class RegionActivation(object):
        SNG_REGION = 1
        RU_REGION = 2
        RU_POL_REGION = 3
        CHOICES = (
            (SNG_REGION, 'Страны СНГ'),
            (RU_REGION, 'Россия'),
            (RU_POL_REGION, 'Россия/Польша'),
        )


class PartnerName(object):
        STEAMBUY = 1
        SFERA2002 = 2
        CHOICES = (
            (STEAMBUY, 'steambuy.com'),
            (SFERA2002, 'sfera2002 на plati.ru'),
        )


class Game(models.Model):
    title = models.CharField(
        'Название игры',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    description = models.TextField(
        'Описание игры',
        blank=True)

    date_created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True)

    date_release = models.DateField(
        'Дата выхода',
        blank=True, null=True)

    genre = models.ManyToManyField(
        'Genre',
        verbose_name='Жанр',
        related_name='genres',
        blank=True)

    mode = models.ManyToManyField(
        'Mode',
        verbose_name='Режим',
        related_name='modes',
        blank=True)

    publisher = models.ForeignKey(
        'Publisher',
        verbose_name='Издатель',
        related_name='publishers',
        blank=True, null=True, on_delete=models.SET_NULL)

    language = models.IntegerField(
        'Язык',
        choices=GameLanguage.CHOICES,
        db_index=True, blank=True, null=True)

    store_activation = models.IntegerField(
        'активация',
        choices=StoreActivation.CHOICES,
        db_index=True, blank=True, null=True)

    method_activation = models.IntegerField(
        'способ активации',
        choices=MethodActivation.CHOICES,
        db_index=True, blank=True, null=True)

    region = models.IntegerField(
        'Региональные ограничения',
        choices=RegionActivation.CHOICES,
        db_index=True, blank=True, null=True)

    image = models.ImageField(
        'Обложка',
        blank=True, null=True,
        upload_to='gamescover/')

    image_slide = models.ImageField(
        'Изображение для слайда',
        blank=True, null=True,
        upload_to='gamescover/')

    my_coast = models.IntegerField(
        'Стоимость в рублях',
        blank=True, null=True)

    id_video = models.CharField(
        'ID youtube ролика',
        max_length=254,
        blank=True, null=True)

    in_stock = models.BooleanField(
        'Товар в наличии',
        default=False)

    store_coast = models.IntegerField(
        'Официальная стоимость',
        blank=True, null=True)

    digiseller_id = models.IntegerField(
        'Digiseller ID',
        blank=True, null=True)

    os = models.CharField(
        'ОС',
        max_length=254,
        blank=True, null=True)

    processor = models.CharField(
        'Процессор',
        max_length=1000,
        blank=True, null=True)

    ozu = models.CharField(
        'Оперативная память',
        max_length=254,
        blank=True, null=True)

    video_card = models.CharField(
        'Видеокарта',
        max_length=1000,
        blank=True, null=True)

    hdd = models.CharField(
        'Жесткий диск',
        max_length=254,
        blank=True, null=True)

    is_slide = models.BooleanField(
        'Показать в слайде',
        default=False)

    is_soon = models.BooleanField(
        'Скоро в продаже',
        default=False)

    on_main_page = models.BooleanField(
        'Показать на главной',
        default=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        if not self.slug:
            self.slug = slugify(self.title)

    @property
    def percent(self):
        return 100 - int(self.my_coast / self.store_coast * 100)

    @property
    def gamevideo(self):
        if self.id_video:
            return mark_safe(
                '<div class="description"><h2>Трейлер игры</h2><div class="video-content"><div class="video-container"><iframe width="560" height="315" src="https://www.youtube.com/embed/{video}?rel=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div></div></div>'.format(video=self.id_video))
        return ''

    def get_absolute_url(self):
        return reverse('games:detail', args=[self.slug])


class Screenshot(models.Model):
    title = models.CharField(
        'Название игры',
        max_length=254)

    image = models.ImageField(
        'Скриншот',
        blank=True, null=True,
        upload_to='gallery/')

    game = models.ForeignKey(
        'Game',
        verbose_name='Скриншоты',
        related_name='screenshots',
        blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Скриншот'
        verbose_name_plural = 'Скриншоты'

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(
        'Название жанра',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    order = models.PositiveSmallIntegerField(
        'Порядок',
        default=0, blank=False, null=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['order']
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        self.slug = slugify(self.title)


class Mode(models.Model):
    title = models.CharField(
        'Название режима',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True)

    order = models.PositiveSmallIntegerField(
        'Порядок',
        default=0, blank=False, null=False)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['order']
        verbose_name = 'Режим'
        verbose_name_plural = 'Режимы'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        self.slug = slugify(self.title)


class Publisher(models.Model):
    title = models.CharField(
        'Название издателя',
        max_length=254)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'

    def __str__(self):
        return self.title


class Partner(models.Model):
    partner_title = models.IntegerField(
        'Название партнера',
        choices=PartnerName.CHOICES,
        db_index=True, blank=True, null=True)

    partner_digi_id = models.CharField(
        'ID товара',
        max_length=254)

    game = models.ForeignKey(
        'Game',
        verbose_name='Партнеры',
        related_name='partners',
        blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['partner_title']
        verbose_name = 'Партнер'
        verbose_name_plural = 'Партнеры'

    def __str__(self):
        return self.get_partner_title_display()

key_market/apps/news/models.py
from django.db import models
from django.urls import reverse

from pytils.translit import slugify


class Item(models.Model):
    title = models.CharField(
        'Название новости',
        max_length=254)

    slug = models.SlugField(
        'slug',
        blank=True,
        max_length=254)

    image = models.ImageField(
        'Изображение для анонса',
        blank=True, null=True,
        upload_to='uploads/')

    short_text = models.TextField(
        'Анонс новости',
        blank=True)

    full_text = models.TextField(
        'Текст новости',
        blank=True)

    date_created = models.DateTimeField(
        'Дата новости',
        auto_now_add=True)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['title']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.autoslug()
        super().save(*args, **kwargs)

    def autoslug(self):
        self.slug = slugify(self.title)

    def get_absolute_url(self):
        return reverse('news:readevent', args=[self.slug])

key_market/apps/users/models.py
from django.db import models


class User(models.Model):
    mail = models.EmailField(
        'E-mail пользователя',
        max_length=254)

    date_created = models.DateTimeField(
        'Дата создания записи',
        auto_now_add=True)

    class Meta:
        default_related_name = 'Без названия'
        ordering = ['date_created']
        verbose_name = 'Электронный адрес'
        verbose_name_plural = 'Электронные адреса'

    def __str__(self):
        return self.mail

key_market/apps/games/forms.py
from django import forms

from games.models import Game


class CheckboxWidget(forms.CheckboxSelectMultiple):
    template_name = 'form/checkbox.html'


class FilterForm(forms.ModelForm):
    """
    Форма для фильтрации игр по параметрам.
    """
    price_min = forms.IntegerField(
        label='Цена от',
        required=False)
    price_max = forms.IntegerField(
        label='Цена до',
        required=False)

    class Meta:
        fields = ['price_min', 'price_max', 'genre', 'store_activation',
                  'mode']
        model = Game
        widgets = {
            'genre': CheckboxWidget,
            'store_activation': CheckboxWidget,
            'mode': CheckboxWidget,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        store_field = self.fields['store_activation']
        store_field.choices = store_field.choices[1:]

key_market/apps/users/forms.py
from django import forms

from users.models import User


class MailForm(forms.ModelForm):
    payment = forms.CharField(
        label='способ оплаты',
        required=True)

    class Meta:
        model = User
        fields = '__all__'

key_market/apps/news/views.py
from django.views.generic import ListView, DetailView
from news.models import Item


class NewsList(ListView):
    model = Item
    template_name = "news_list.html"


class NewsDetail(DetailView):
    model = Item
    template_name = "news_detail.html"

key_market/apps/pages/views.py
from django.views.generic.base import TemplateView

from games.utils import fetch_reviews


class AgreementDoc(TemplateView):
    template_name = "pages_agreement.html"


class ActivationPage(TemplateView):
    template_name = "pages_activation.html"


class GuaranteePage(TemplateView):
    template_name = "pages_guarantee.html"


class PaymentPage(TemplateView):
    template_name = "pages_payment.html"


class InstructionPage(TemplateView):
    template_name = "pages_instruction.html"


class SupportPage(TemplateView):
    template_name = "pages_support.html"


class ReviewsPage(TemplateView):
    template_name = "pages_reviews.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'reviews': fetch_reviews(),
        })
        return context

key_market/templates/base.html
{% load static pipeline %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}STEAMCOOL. Интернет-магазин лицензионных ключей для игр на PC{% endblock title %}</title>
    <meta name="keywords" content="{% block keywords %}магазин ключей, ключи steam, ключи origin, ключи uplay, со скидкой, купить ключ {% endblock keywords %}" />
    <meta name="description" content="{% block description %}Магазин лицензионных steam, origin, uplay ключей по низким ценам.{% endblock description %}" />

    
    <meta property="og:title" content="{% block ogtitle %}STEAMCOOL. Интернет-магазин лицензионных ключей для игр на PC{% endblock ogtitle %}" />
    <meta property="og:description" content="{% block ogdescription %}Интерент-магазин лицензионных ключей steam, origin, uplay по низким ценам.{% endblock ogdescription %}" />
    <meta property="og:image" content="{% block ogimg %}{% static 'frontend/images/logo-350.png' %}{% endblock ogimg %}"/>


    <link rel="stylesheet" type="text/css" href="{% static 'frontend/style/css.css' %}?v=7" />
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/style/responsive.css' %}?v=7" />
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/style/nouislider.css' %}?v=7" />
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/style/fancybox.css' %}?v=7" />
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/style/swiper.css' %}?v=7" />
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/font-awesome/css/font-awesome.min.css' %}">

    {% block scripts %}
        {% javascript 'libs' %}
            <script type="text/javascript" src="{% static 'frontend/js/fancybox.js' %}?v=7"></script>
            <script type="text/javascript" src="{% static 'frontend/js/nouislider.js' %}?v=7"></script>
            <script type="text/javascript" src="{% static 'frontend/js/swiper.min.js' %}?v=7"></script>
            <script type="text/javascript" src="{% static 'frontend/js/settings.js' %}?v=7"></script>
        {% javascript 'frontend' %}
    {% endblock %}
    
    {% block extra-styles %}{% endblock extra-styles %}

    {% block extra-scripts %}{% endblock extra-scripts %}

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />

    
</head>
<body>
    <div class="wrapper">
        <div class="head">
            <div class="logo">
                <a href="/">
                    <img src="{% static 'frontend/images/logo-big-ic.png' %}">
                    <img src="{% static 'frontend/images/logo-big-steamcool.png' %}">
                    <img src="{% static 'frontend/images/logo-big-info.png' %}">
                </a>
            </div>
            <div data-popup="search" class="search">
                <div class="head_popup">
                    <span class="close_popup_button">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </span>
                </div>
                <form action="">
                    <div class="search-text">
                        <input autocomplete="off" class="place" id="game-search" type="text" placeholder="Введите название игры ...">
                    </div>
                    <div class="search-submit">
                        <input type="submit" value="Найти">
                    </div>
                </form>
            </div>
            <div data-popup="book" class="book">
                <div class="head_popup">
                    <span class="close_popup_button">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </span>
                </div>
                <div class="books">
                    <div class="books_head">Алфавитный указатель</div>
                    {% for symbol in alphabet %}
                        <a class="{% if alphabet_symbol == symbol %}active{% endif %}" href="{% url 'games:list' %}?query={{symbol}}">
                            {{ symbol|title }}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="mobile_navigation">
                <div data-popup-button="search" class="search_button">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </div>
                <div data-popup-button="book" class="book_button">
                    <span>a-z</span>
                </div>
                <div data-popup-button="navigation" class="sandvich_button">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper">   
        <div data-popup="navigation" class="navigation">
            <div class="head_popup">
                <span class="close_popup_button">
                    <i class="fa fa-times" aria-hidden="true"></i>
                </span>
            </div>
            <div class="menu">
                <ul>
                    <li><a href="{% url 'games:list' %}">Каталог игр</a></li>
                    <li><a href="{% url 'pages:reviews' %}">Отзывы</a></li>
                    <li><a href="{% url 'pages:instruction' %}">Как купить</a></li>
                    <li><a href="{% url 'pages:guarantees' %}">Гарантии</a></li>
                    <li><a href="{% url 'pages:support' %}">Поддержка</a></li>
                    <li><a href="{% url 'pages:payment' %}">Способы оплаты</a></li>
                    <li><a target="_blank" href="https://www.oplata.info/info/">Мои покупки</a></li>
                    <li><a class="lucky-button" href="{% url 'games:genre_list' 'ispyitaj-udachu' %}">Испытай удачу</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="wrapper">
        <div class="columns">
            {% block content %}{% endblock content %}
        </div>
    </div>
    <div class="wrapper">
        <div class="footer">
            <div class="footer_columns">
                <div class="menu">
                    <span>О магазине</span>
                    <ul>
                        <li><a href="{% url 'pages:reviews' %}">Отзывы</a></li>
                        <li><a href="{% url 'pages:guarantees' %}">Гарантии</a></li>
                        <li><a href="{% url 'pages:instruction' %}">Как купить</a></li>
                        <li><a href="{% url 'pages:payment' %}">Способы оплаты</a></li>
                        <li><a href="{% url 'pages:support' %}">Поддержка</a></li>
                        <li><a target="_blank" href="https://www.oplata.info/info/">Мои покупки</a></li>
                    </ul>
                </div>
                <div class="menu">
                    <span>Ключи активации</span>
                    <ul>
                        <li><a href="{% url 'games:list' %}?store_activation=1">Steam</a></li>
                        <li><a href="{% url 'games:list' %}?store_activation=2">Origin</a></li>
                        <li><a href="{% url 'games:list' %}?store_activation=3">Uplay</a></li>
                        <li><a href="{% url 'games:list' %}?store_activation=4">Rockstar</a></li>
                    </ul>
                </div>
                <div class="footer_info">
                    <span>Контакты</span>
                    <div class="mail">
                        Технический отдел:<br />
                        <i class="fa fa-envelope-open" aria-hidden="true"></i>
                        <a href="mailto:support@steamcool.ru">support@steamcool.ru</a>
                    </div>
                    <div class="mail">
                        Предложения сотрудничества:<br />
                        <i class="fa fa-envelope-open" aria-hidden="true"></i>
                        <a href="mailto:info@steamcool.ru">info@steamcool.ru</a>
                    </div>
                </div>
                <div class="footer_info">
                    <span>Информация</span>

                    <p>Все лицензионный ключи закупаются у официальных диллеров, которые закупают цифровой товар у известных издателей, таких как: 1C, 2K, Bandai Namco, Curve Digital, Capcom, Codemasters, Deep Silver, Disney, IO Interactive, Iceberg Interactive, Nordic Games, Paradox, Plug-in-Digital, Take-Two Interactive, Team17, Ubisoft, Бука, Новый Диск и другие.</p>

                    <p>Магазин не занимается продажей аккаунтов.</p>
                </div>
            </div>
        </div>
    </div>


<!--
<div class="footer clear-block">
    <div class="footer-col">
        <span>Товары</span>
        <ul>
            {% for store in store_list %}
                <li>
                    <a href="{% url 'games:store_list' store %}">
                        {{ store|title }} ключи
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="footer-col">
        <span>Наш магазин</span>
        <ul>
            <li><a href="{% url 'pages:reviews' %}">Отзывы</a></li>
            <li><a href="{% url 'pages:payment' %}">Способы оплаты</a></li>
            <li><a href="{% url 'pages:guarantees' %}">Гарантии</a></li>
        </ul>
    </div>
    <div class="footer-col">
        <span>Помощь</span>
        <ul>
            <li><a href="{% url 'pages:support' %}">Поддержка</a></li>
            <li><a href="{% url 'pages:instruction' %}">Как купить</a></li>
            <li><a href="{% url 'pages:activation' %}">Как активировать покупку</a></li>
            <li><a target="_blank" href="https://www.oplata.info/info/">Мои покупки</a></li>
        </ul>
    </div>
    <div class="footer-logo">
        <a href="#"><img src="{% static 'frontend/images/logo-big.png' %}" width="100%"></a>
    </div>
</div>
<div class="footer-copy">
    Все права защищены. Полное или частичное копирование материалов сайта без согласования с администрацией запрещено!
</div>
-->





<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter23554624 = new Ya.Metrika({
                    id:23554624,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/23554624" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>

key_market/templates/columns_1.html
{% extends "base.html" %}

{% block content %}
    <div class="big_center">
        {% block view_element %}{% endblock view_element %}
    </div>
{% endblock content %}

key_market/templates/columns_2.html
{% extends "base.html" %}

{% block content %}
    <div class="left">
        {% block left_column %}
            {% include "games_genre_list.html" %}
        {% endblock left_column %}
    </div>
    <div class="big_center">
        {% block view_element %}{% endblock view_element %}
    </div>
    {% block block_comments %}{% endblock block_comments %}
{% endblock content %}

key_market/templates/columns_3.html
{% extends "base.html" %}

{% load static pipeline %}

{% block content %}
    <div class="left">
        {% block left_column %}
            {% include "games_genre_list.html" %}
        {% endblock left_column %}
    </div>
    <div class="center">
        {% block center_column %}{% endblock center_column %}
    </div>
    <div class="right">
        {% block right_column %}
            {% include "games_last_pay.html" %}
            <!--{% include "games_soon_block.html" %}-->
        {% endblock right_column %}
    </div>
{% endblock content %}

key_market/templates/paginator.html
{% load common_tags %}

<div class="pager">
   <ul>
   {% if page_obj.has_previous %}
      <li class="prev"><a href="?{% pagination_url page_obj.previous_page_number %}">...назад</a></li>
   {% endif %}
   {% if show_first %}
      <li><a href="?{% pagination_url 1 %}">1</a></li>
      <li><span>...</span></li>
   {% endif %}
   {% for linkpage in page_numbers %}
      {% ifequal linkpage page %}
         <li class="current"><span>{{ page }}</span></li>
      {% else %}
         <li><a href="?{% pagination_url linkpage %}">{{ linkpage }}</a></li>
      {% endifequal %}
   {% endfor %}
   {% if show_last %}
      <li><span>...</span></li>
      <li><a href="?{% pagination_url 'last' %}">{{ pages }}</a></li>
   {% endif %}
   {% if page_obj.has_next %}
      <li class="next"><a href="?{% pagination_url page_obj.next_page_number %}">далее...</a></li>
   {% endif %}
   </ul>
</div>

key_market/templates/yandex.html
c4d68f9c7f93